ministryofjustice/hale-platform

.gitignore
bin/build.sh
bin/upload.sh
composer.lock
makefile
opt/php/load.php
opt/scripts/config.sh
wp.dockerfile

* Script that triggers if you have an uploads/ folder in root. Will copy contents into wordpress/wp-content/uploads on `make run` command. This saves you having to populate that folder when it gets wiped out when you run `make build`.
* Wrapped conditional around `s3-uploads` plugin. This was causing issues running locally but now means the plugin is off when working locally.
* Fixed wp-config.php constant that wasn't set correctly and was causing error.
* Upgraded WP to latest version.

Minor modifications to better improve working on local environment

---

helm_deploy/wordpress/templates/ingress.yaml

Domains added
- magistrates.judiciary.uk
- victimscommissioner.org.uk
- publicdefenderservice.org.uk
- ccrc.gov.uk

Remove IMB and test domain

---

helm_deploy/wordpress/templates/ingress.yaml

Setup the ModSecurity firewall WAF

Enable CP WAF modsec

---

docker-compose.yml

Having this in caused issues when running Docker locally.

Remove duplicate virtual port causing error

---

docker-compose.yml
helm_deploy/wordpress/templates/ingress.yaml

* Add IMB cert
* Add IMB host reference

Hale platform IMB domain switch

---

helm_deploy/wordpress/templates/deployment.yaml

* Modify container readiness timings
* Add Readiness probe to NGINX

Probe updates

---

helm_deploy/wordpress/templates/ingress.yaml

Add BrookHouse domain to certs manifest and multisite routing manifest.

Update Brookhouse domain creds in ingress

---

.github/workflows/rw-build-image.yaml
composer.json

Add the Hale Dash child theme. This provides a dashboard of key metrics for the multisite.

Add Hale Dash child theme

---

composer.json
opt/php/load.php

Several plugins have now merged into one plugin called Hale Components.

Hale component merge

---

composer.json

FME plugin became discontinued so we had to add it to our own private repo as it is still used on Brookhouse.

Footnotes Made Easy plugin change

---

wordpress.dockerfile

Tested on dev. Looks okay, mainly changes to Full Site Editor which we're not currently using.

Upgrade WordPress to 6.5

---

helm_deploy/wordpress/values.yaml

We want to setup a looping option in our ingress to improve how we manage domains in it.

Add domains as host values to allow new Helm ingress

---

wordpress.dockerfile

* Updates WP with latest version 6.5.3
* Updates Hale Components to include new Taxonomy Updater tool

Update WP version to latest version 6.5.3 & Tax Updater tool

---

wordpress.dockerfile

https://wordpress.org/documentation/wordpress-version/version-6-5-4/

Update WordPress short-cycle release bug fix

---

.github/workflows/cd.yaml
.github/workflows/rw-build-image.yaml

* Change ECR vars to secrets to fix issue with recent CP update to ECR 7.0
* Test addition of caching to GitAction workflow

Fix gitaction error

---

makefile
wordpress.dockerfile

Upgrade WP dockerfile 6.6

---

.gitignore
helm_deploy/wordpress/templates/ingress.yaml

Test a more targeted WAF config, with specific rules and to a higher threshold. We've tested on Dev, Staging and Prod.

Add new WAF config

---

helm_deploy/wordpress/templates/ingress.yaml

Report on IMB members site of WAF error.

Add new WAF rule to ingress

---

helm_deploy/wordpress/templates/ingress.yaml

Removed the IPs from staging allowlist and added a new WAF exclusion. Also formatted in numerical order for easier reading.

Update waf rules

---

helm_deploy/wordpress/templates/ingress.yaml

Added new rule after error found on playground

Added new ingress rule

---

helm_deploy/wordpress/templates/ingress.yaml

Removed trailing ? for uri and added new rule exception for json API.

Amended URL request URI

---

helm_deploy/wordpress/templates/ingress.yaml

amend redirect so org redirects to gov.uk

amend iapdci redirect

---

.github/workflows/cd.yaml
.github/workflows/rw-build-image.yaml
helm_deploy/wordpress/templates/ingress.yaml
helm_deploy/wordpress/templates/secrets.yaml
helm_deploy/wordpress/values.yaml

updated various secret locations to test new variable

waf variable testing

---

helm_deploy/wordpress/templates/ingress.yaml

updated ruleid as duplicate existed

Updated ruleid as contained a duplicate

---

helm_deploy/wordpress/templates/ingress.yaml

simplified the policy for editors and everyone else

Simplified waf config for authenticated or not

---

helm_deploy/wordpress/templates/ingress.yaml

Updated code in an attempt to make it cleaner

---

.github/workflows/cd.yaml
.github/workflows/rw-build-image.yaml
helm_deploy/wordpress/templates/ingress.yaml
helm_deploy/wordpress/templates/secrets.yaml

Added changes from DEV to DEMO and updated secrets

Added WAF changes for testing

---

helm_deploy/wordpress/templates/ingress.yaml
helm_deploy/wordpress/templates/secrets.yaml

Updated to show new waf policy

Waf policy changes

---

wordpress.dockerfile

* Tested on demo, looks good. Mostly changes to FSE.
For more info https://wordpress.com/blog/2024/11/12/wordpress-6-7/

Increase WP version to 6.7

---

helm_deploy/wordpress/templates/ingress.yaml

Checks for cookie in the header phase then adds detectiononly and not the body

Changed phase to check

---

composer.json

Adds latest version of hale with hearing template

Update Hale theme with new hearing template

---

.github/workflows/rw-build-image.yaml
bin/build.sh

Old themes no longer used on the platform

Remove compiling assets for themes not used
